# This Rakefile has all the right settings to run the tests inside each chapter
gem 'rspec', '~>2'
require 'rspec/core/rake_task'

task :default => :spec

desc "run tests for this chapter"
RSpec::Core::RakeTask.new do |task|
  task.pattern = "*_spec.rb"
  task.rspec_opts = [ '-I..', '-I.', '-Isolution', '-f documentation', '-r ../rspec_config', '--color']
  task.verbose = false
end
